//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Praktika
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RealEstateEntities : DbContext
    {
        public RealEstateEntities()
            : base("name=RealEstateEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Agent> Agent { get; set; }
        public virtual DbSet<Apartment> Apartment { get; set; }
        public virtual DbSet<ApartmentDemand> ApartmentDemand { get; set; }
        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<Demand> Demand { get; set; }
        public virtual DbSet<District> District { get; set; }
        public virtual DbSet<House> House { get; set; }
        public virtual DbSet<HouseDemand> HouseDemand { get; set; }
        public virtual DbSet<Land> Land { get; set; }
        public virtual DbSet<LandDemand> LandDemand { get; set; }
        public virtual DbSet<RealEstate> RealEstate { get; set; }
        public virtual DbSet<Supply> Supply { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TypeRealEstate> TypeRealEstate { get; set; }
    }
}
